### ISSUE TITLE
OPF problem

### ISSUE THREAD

**Issue by dimendozao** [Gurobi/gurobi-optimods#123]
**Describe the bug**
The AC OPF is giving an infeasible solution for a case.

**To Reproduce**

- Run an OPF for attached case in MATPOWER and check infeasibility in power balance equations. 
- Save the case as .MAT file (It is attached as well).
- Load it in a python distribution with the command opf.read_case_matpower("file.mat") after importing optimod modules
- Run the AC OPF. 
- Check if solutions match.
- Check infeasibility the same way as before.

MATPOWER case file (.m) and Optimod case (.mat)
[IEEE69.zip](https://github.com/Gurobi/gurobi-optimods/files/13241332/IEEE69.zip)

**Expected behavior**
If the optimization problem was solved and the optimal solution was found, the solution must be feasible within tolerance. I expected the same solution as MATPOWER.

**Additional context**

With MATPOWER I run the OPF for a case (69 node Radial network, 1 reference node (node 1), 68 PQ nodes (2-69)) , whose cost function is polynomial (default in MATPOWER) with zero coefficients, except for the first order one (linear cost function). With this setup, we are minimizing indirectly the power in the slack generator, thus the losses.

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/3c68b78d-3d5d-4aec-9cd5-5796d06a6b75) 
![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/71d6a8c1-f428-4ead-8b95-a3398ab31775)

To verify feasibility, we use the obtained solution and check if the voltages are within limits and if the power balance equations are satisfied (in this case the line power limits are unconstrained). 

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/afc71c93-8767-4efb-b1bb-2f76d4923a70)

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/d3acebe3-db67-4f4c-9d73-a558422ae8fb)

To check balance equations I use 2 tests:

1. First, create a zero array (size Nx1) for the active $p_{g}$ and reactive power $q_{g}$ at the slack bus and the demand ($p_{d}, q_{d}$) for each node, and assign the values from the solution obtained accordingly. Calculate the power losses $p_{loss},q_{loss}$. Then check power balance equations:

$$ \sum_{i=1}^{N} p_{g} - \sum_{i=1}^{N} p_{d} -p_{loss} =0$$

$$ \sum_{i=1}^{N} q_{g} - \sum_{i=1}^{N} q_{d} -q_{loss} =0$$

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/658eaeb9-8530-4445-b6f1-3d49001a5cfb)
![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/77d5041b-4183-468c-a489-8eb3de808463)

2.  Choose a power flow model, compute to each corresponding variable its values from the solution and calculate for each node the power balance equation. For instance, if the complex bus injection model is chosen, the complex admittance matrix $Y$, voltage $V_{i}$, generation $S_{i}^{g}$ and load $S_{i}^{d}$ vectors should be constructed.

$$ S_{i}^{g} -S_{i}^{d} = V_{i} \sum_{j=1}^{N} Y_{ij}^{\ast}V_{j}^{\ast} \quad \forall i,j \in N$$

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/d5d3198a-1fdb-469d-a5a8-2d8f44e10613)

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/5d4bf136-95d5-47d4-a62c-bbb93655d788)

As observed, the MATPOWER solution is feasible, and is often found as reference value in the literature.

Applying the same procedure in python. First, the modules are imported, and the case is loaded. Then the AC OPF is excecuted:

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/83d51e43-c8c6-483c-b6ba-c022dc8f91c1)

The objective differs from MATPOWER, but the solution found is optimal.

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/65488656-3642-4f5c-81b6-d449c521d1d0)

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/64bda85e-b082-4bc8-be00-b3514d88ddfd)
![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/1a87876a-f50d-4f2f-88fd-bbfd27d738f4)

This solution pass the first feasibility check:

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/cee7b4b1-9315-472e-b98f-241238f05371)
![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/63b33a7f-3bd5-4c03-8e06-5b98113ffbed)

However the second feasibility check is failed:

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/14d9d215-b153-481f-b7cc-0b21026843cc)

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/6e814632-6aff-4ff7-b778-cadd2738d854)

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/ef443684-4663-4ce0-a19f-16691310fb14)

**Comment by simonbowly** [comment]
Hi @dimendozao, thanks for raising this. Could you please attach the code necessary to reproduce this result from your input files as a python script? We appreciate you sharing a working example, but transcribing code from screenshots is time consuming and error-prone.

In addition, can you please share the versions of installed packages required to reproduce the issue (python, gurobipy, gurobi-optimods) and the OS you are running?

**Comment by dimendozao** [comment]
Hi @simonbowly. Thanks for your reply. I used the following setup:

-  Windows 11 22H2
-  Python 3.11
-  Anaconda 3
-  Spyder IDE 5.4.3  
-  gurobipy version 10.0.2
-  gurobi-optimods version 1.1.0
-  numpy 1.24.3

Here is the .py file.

[IEEE69.zip](https://github.com/Gurobi/gurobi-optimods/files/13250484/IEEE69.zip)

**Comment by simonbowly** [comment]
Hi @dimendozao, sorry for the delay! I could reproduce this with your code, thanks for sharing.

I believe this is linked to the rectangular coordinates representation currently used for the AC formulation. Gurobi doesn't report any large infeasibility in the solution itself, so the formulation would seem to be the issue here. We haven't added a polar form representation (which I believe MATPOWER uses?) to the optimod just yet, but this is planned for early next year.

**Comment by hhijazi** [comment]
One thing I noticed is that the line limits are set to 0 in the m file. I would also recommend using the per unit numerical values in the matrices and avoid having the per unit conversion done inside the file.
I'm attaching an updated m file (fixed line limit and per unit issues) that returns an optimal solution with an active power of 3.8921 (optimal objective of 77.842).
I'm also attaching the solution file if that helps.
[Archive.zip](https://github.com/Gurobi/gurobi-optimods/files/14517423/Archive.zip)

**Comment by 100110110101** [comment]
Hi @dimendozao & @simonbowly,

after talking with @JaromilNajman over the opf-optimod last week, I tried it myself and came across this issue here.

I was also able to reproduce the issue, although I found 3 slightly different solutions with Gurobi than dimendozao did:
Solution count 3: 80.886 80.9328 80.9432
Maybe this is because I am using Gurobi 11.0.1.
However, I think these different solutions are not the important point here. I think the important point here are the power differences at the buses, which show up for any arbitrary solution when the node powers are calculated from the generator and load powers on the one hand and from the grid equation system with the complex valued voltages on the other hand.
I did some more investigations because I couldn't believe that the use of rectangular coordinates could be the cause of such large deviations.

Long story short: I am pretty sure that the voltage angles are calculated incorrectly.
I didn't elaborate what the function `compute_voltage_angles(alldata, result)` in grbformulator.py is supposed to do in detail (I think I have a rough idea ...) but I think this function is way to complicated and maybe there is an error in it. However, I commented the according function-call in line 372 of grbformulator.py out and added the following simple line in the for-loop starting in line 345:
`resbus["Va"] = math.atan(alldata["LP"]["fvar"][databus].X/alldata["LP"]["evar"][databus].X)`
Furthermore, the angle is calculated with `ph[i]=np.radians(res_bus[i]['Va'])` in dimendozao's OptimodTest.py, but I think it simply needs to be `ph[i]=res_bus[i]['Va']`.
With both adjustments significantly better (and reasonable) values can be calculated and less differences result at each node. 

Can you reproduce the improvements with your code?

P.S.: It is still unsatisfactory that the remaining differences are so large. There is certainly still room for improvement.
From my experience with rectangular coordinates, I would generally recommend not to switch from rectangular coordinates to polar coordinates and back, as the (inverse) trigonometric functions entail numerical inaccuracies.

**Comment by hhijazi** [comment]
Hi folks, we believe that we found the issue and can get all violations down to zero. It has to do with using auxiliary variables in the power flow constraints, and this particular instance has numerically large coefficients (1e6) multiplying these variables.
The solution is to have the power flow constraints written using the original variables ((e,f) for complex V).
We are working on an updated model, stay tuned.

**Comment by dimendozao** [comment]
Hi everyone,

I am checking the response given by Thomas @100110110101 regarding the computation of phase angles. The calculated infeasibility in the code is indeed substantially reduced by not transforming the angles into radians, as suggested.

![imagen](https://github.com/Gurobi/gurobi-optimods/assets/138025704/1875f68c-6a98-4e44-890f-129a24db7255)

This issue could appear naturally if the results are said to be formatted as MATPOWER results, since according to their manual phase angles are displayed in degrees. This raises the question if the solution obtained from optimods delivers the angles in degrees or radians.
